import unittest
import json

from kbextractor.plugins.sources.pydesk import PyDesk


class TestPyDesk(unittest.TestCase):
    topics_no_next = json.loads('{"total_entries":5,"_links":{"self":{"href":"/api/v2/topics?page=1&per_page=50","class":"page"},"first":{"href":"/api/v2/topics?page=1&per_page=50","class":"page"},"last":{"href":"/api/v2/topics?page=1&per_page=50","class":"page"},"previous":null,"next":null},"_embedded":{"entries":[{"name":"Sample :: General","description":"Sample Topic Description :: Information about our company","position":1,"allow_questions":true,"in_support_center":true,"created_at":"2014-03-15T22:45:16Z","updated_at":"2014-03-15T22:45:16Z","_links":{"self":{"href":"/api/v2/topics/633385","class":"topic"},"articles":{"href":"/api/v2/topics/633385/articles","class":"article"},"translations":{"href":"/api/v2/topics/633385/translations","class":"topic_translation"}}},{"name":"Canned Responses","description":"Internal responses to common questions","position":2,"allow_questions":true,"in_support_center":false,"created_at":"2014-03-15T22:45:16Z","updated_at":"2014-03-15T22:45:16Z","_links":{"self":{"href":"/api/v2/topics/633386","class":"topic"},"articles":{"href":"/api/v2/topics/633386/articles","class":"article"},"translations":{"href":"/api/v2/topics/633386/translations","class":"topic_translation"}}},{"name":"Sample :: Products","description":"Sample Topic Description :: Information about our products","position":3,"allow_questions":true,"in_support_center":true,"created_at":"2014-03-15T22:45:16Z","updated_at":"2014-03-15T22:45:16Z","_links":{"self":{"href":"/api/v2/topics/633387","class":"topic"},"articles":{"href":"/api/v2/topics/633387/articles","class":"article"},"translations":{"href":"/api/v2/topics/633387/translations","class":"topic_translation"}}},{"name":"Spanish Jokes","description":"Testing","position":4,"allow_questions":true,"in_support_center":true,"created_at":"2014-03-15T23:35:52Z","updated_at":"2014-03-18T03:11:52Z","_links":{"self":{"href":"/api/v2/topics/633391","class":"topic"},"articles":{"href":"/api/v2/topics/633391/articles","class":"article"},"translations":{"href":"/api/v2/topics/633391/translations","class":"topic_translation"}}},{"name":"French Jokes","description":"Topic --> Article","position":5,"allow_questions":true,"in_support_center":true,"created_at":"2014-03-18T02:52:43Z","updated_at":"2014-03-18T03:01:47Z","_links":{"self":{"href":"/api/v2/topics/634048","class":"topic"},"articles":{"href":"/api/v2/topics/634048/articles","class":"article"},"translations":{"href":"/api/v2/topics/634048/translations","class":"topic_translation"}}}]}}')
    user_next = json.loads('{ "total_entries": 110, "_links": { "self": { "href": "/api/v2/users?page=2&per_page=2", "class": "page" }, "first": { "href": "/api/v2/users?page=1&per_page=2", "class": "page" }, "last": { "href": "/api/v2/users?page=55&per_page=2", "class": "page" }, "next": { "href": "/api/v2/users?page=3&per_page=2", "class": "page" }, "previous": { "href": "/api/v2/users?page=55&per_page=2", "class": "page" } }, "_embedded": { "entries": [ { "id": 1, "name": "John Doe", "public_name": "John Doe", "email": "john@acme.com", "level": "agent", "created_at": "2013-03-13T19:56:56Z", "updated_at": "2014-03-06T20:56:56Z", "current_login_at": "2014-03-12T19:56:56Z", "last_login_at": "2014-03-06T20:56:56Z", "_links": { "self": { "href": "/api/v2/users/1", "class": "user" }, "preferences": { "href": "/api/v2/users/1/preferences", "class": "user_preference" }, "macros": { "href": "/api/v2/users/1/macros", "class": "macro" }, "filters": { "href": "/api/v2/users/1/filters", "class": "filter" }, "integration_urls": { "href": "/api/v2/users/1/filters", "class": "integration_url" }, "groups": { "href": "/api/v2/users/1/groups", "class": "group" }, "searches": { "href": "/api/v2/users/1/searches", "class": "search" } } }, { "id": 1, "name": "John Doe", "public_name": "John Doe", "email": "john@acme.com", "level": "agent", "created_at": "2013-03-13T19:56:56Z", "updated_at": "2014-03-06T20:56:56Z", "current_login_at": "2014-03-12T19:56:56Z", "last_login_at": "2014-03-06T20:56:56Z", "_links": { "self": { "href": "/api/v2/users/1", "class": "user" }, "preferences": { "href": "/api/v2/users/1/preferences", "class": "user_preference" }, "macros": { "href": "/api/v2/users/1/macros", "class": "macro" }, "filters": { "href": "/api/v2/users/1/filters", "class": "filter" }, "integration_urls": { "href": "/api/v2/users/1/filters", "class": "integration_url" }, "groups": { "href": "/api/v2/users/1/groups", "class": "group" }, "searches": { "href": "/api/v2/users/1/searches", "class": "search" } } } ] } }')

    def test_no_next_page(self):
        pydesk = PyDesk()
        next_page_url = pydesk.next_page(self.topics_no_next["_links"])
        self.assertIsNone(next_page_url)

    def test_next_page(self):
        pydesk = PyDesk()
        next_page_url = pydesk.next_page(self.user_next["_links"])
        self.assertIsNotNone (next_page_url)

if __name__ == '__main__':
    unittest.main()
